#cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - kms
    - decrypt
    - --location=global
    - --keyring=portfolio27031987
    - --key=authservice
    - --ciphertext-file=./assets/certs/prod.server.enc.crt
    - --plaintext-file=./assets/certs/prod.server.crt

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - kms
    - decrypt
    - --location=global
    - --keyring=portfolio27031987
    - --key=authservice
    - --ciphertext-file=./assets/certs/prod.server.enc.key
    - --plaintext-file=./assets/certs/prod.server.key
    
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/nginx-reverse-proxy', '.' ]

- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'compute', 'instance-groups', 'managed',  'rolling-action', 'restart', 'nginx-reverse-group', '--region=us-east4' ]

images:
- 'gcr.io/$PROJECT_ID/nginx-reverse-proxy'